/* ============================================================
   Flatten public/assets/css/main.css and everything it @imports
   into a single public/assets/css/bundle.css.

       node scripts/build-css.js

   Why: @import chains are resolved serially by the browser, so
   the ~19-file component layout that is pleasant to work in
   costs round trips in production. Develop against main.css,
   ship bundle.css — the cascade is identical because imports are
   inlined in place, depth-first, exactly where they appear.

   Deliberately dumb: no minifier, no autoprefixer, no deps. Font
   URLs are rewritten relative to the bundle's own location.
   ============================================================ */
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const CSS_DIR = path.join(__dirname, "..", "public", "assets", "css");

// One bundle per page. They overlap (both pull in the fonts and the
// receptionist tokens) and that is fine: the point of splitting the
// desk onto its own route is that index.html never downloads the
// chat UI, which a single shared bundle would undo.
const ENTRIES = [
  ["main.css", "bundle.css"],
  ["desk.css", "desk.bundle.css"],
];

const IMPORT = /@import\s+url\(\s*["']([^"']+)["']\s*\)\s*;/g;

let seen = new Set();

function inline(file) {
  const real = path.resolve(file);
  if (seen.has(real)) return `/* (already inlined: ${path.basename(real)}) */`;
  seen.add(real);

  const dir = path.dirname(real);
  const src = fs.readFileSync(real, "utf8");

  return src.replace(IMPORT, (whole, spec) => {
    if (/^(https?:)?\/\//.test(spec)) return whole; // leave remote imports alone
    const target = path.resolve(dir, spec);
    const rel = path.relative(CSS_DIR, target).replace(/\\/g, "/");
    // Rewrite url(...) inside the imported file so asset paths stay correct
    // once its rules move up into the bundle's directory.
    const body = inline(target);
    const fromDir = path.dirname(path.resolve(dir, spec));
    return (
      `\n/* ▼ ${rel} ─────────────────────────────────────── */\n` +
      body.replace(/url\(\s*(["']?)(\.[^"')]+)\1\s*\)/g, (m, q, u) => {
        const abs = path.resolve(fromDir, u);
        const out = path.relative(CSS_DIR, abs).replace(/\\/g, "/");
        return `url("${out.startsWith(".") ? out : "./" + out}")`;
      }) +
      `\n/* ▲ ${rel} */\n`
    );
  });
}

const header = `/* GENERATED by scripts/build-css.js — do not edit.
   Edit the component files under assets/css/ and re-run. */\n`;

for (const [entry, out] of ENTRIES) {
  const src = path.join(CSS_DIR, entry);
  if (!fs.existsSync(src)) {
    console.warn(`skipped ${entry} — not found`);
    continue;
  }
  seen = new Set(); // each bundle inlines its own copy
  const target = path.join(CSS_DIR, out);
  fs.writeFileSync(target, header + inline(src));
  console.log(
    `${entry.padEnd(9)} → ${out.padEnd(17)} ${String(seen.size).padStart(2)} files, ` +
      `${(fs.statSync(target).size / 1024).toFixed(1)} kB`
  );
}
